import type { WorkbenchIconName, WorkbenchProject } from "../../types/project"

export const workbenchCategories = [
  { key: "ai", icon: "brain-circuit", title: "Artificial intelligence" },
  { key: "automation", icon: "workflow", title: "Automation" },
  { key: "files", icon: "folder-open", title: "Files" },
  { key: "games", icon: "gamepad-2", title: "Games" },
  { key: "media", icon: "images", title: "Media" },
  { key: "network", icon: "network", title: "Network" },
] as const satisfies readonly {
  key: string
  icon: WorkbenchIconName
  title: string
}[]

export type WorkbenchCategory = (typeof workbenchCategories)[number]["key"]

export const workbenchProjectEntries = [
  {
    title: "NyaAI",
    path: "workbench/ai/nya-ai",
    updatedAt: "2026-07-11T10:05:30+08:00",
    summary: "OpenAI-compatible Flask chat API with switchable providers.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "ai",
  },
  {
    title: "Auto Crawler",
    path: "workbench/automation/auto-crawler",
    updatedAt: "2026-07-11T10:05:44+08:00",
    summary: "Image-site discovery and batch-download experiment.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "automation",
  },
  {
    title: "Clicker",
    path: "workbench/automation/clicker",
    updatedAt: "2026-07-11T10:05:44+08:00",
    summary: "Windows mouse clicker with global hotkeys and fail-safes.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "automation",
  },
  {
    title: "Scan Image To",
    path: "workbench/files/scan-img-to",
    updatedAt: "2026-07-11T10:06:01+08:00",
    summary: "Multithreaded image scanner and copier with ignore rules.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "files",
  },
  {
    title: "Sync Multi",
    path: "workbench/files/sync-multi",
    updatedAt: "2026-07-11T10:06:01+08:00",
    summary: "Directory watcher and deterministic multi-source backup sync.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "files",
  },
  {
    title: "Gomoku",
    path: "workbench/games/gomoku",
    updatedAt: "2026-07-11T10:06:17+08:00",
    summary: "A 15 × 15 Gomoku game with console and desktop interfaces.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "games",
  },
  {
    title: "Adjust GIF",
    path: "workbench/media/adjust-gif",
    updatedAt: "2026-07-11T10:06:42+08:00",
    summary: "Small desktop utility for changing GIF playback speed.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "media",
  },
  {
    title: "Cedarflake ASCII Art",
    path: "workbench/media/ascii-art",
    updatedAt: "2026-07-11T17:48:28+08:00",
    summary: "Turn images and video into text, rendered frames, and playable ASCII video.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "media",
  },
  {
    title: "Cut Image",
    path: "workbench/media/cut-image",
    updatedAt: "2026-07-11T10:06:42+08:00",
    summary: "Split one image into horizontal slices from the command line.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "media",
  },
  {
    title: "Merge AV",
    path: "workbench/media/merge-av",
    updatedAt: "2026-07-11T10:06:42+08:00",
    summary: "Merge audio and video files through a focused FFmpeg wrapper.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "media",
  },
  {
    title: "Campus Net",
    path: "workbench/network/campus-net",
    updatedAt: "2026-07-11T10:07:05+08:00",
    summary: "Ruijie campus portal auto-login utility for local use.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "network",
  },
] as const satisfies readonly WorkbenchProject<WorkbenchCategory>[]
