packages:
  - "apps/*"
  - "packages/*"

nodeVersion: 22.22.2
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true

overrides:
  use-sync-external-store: 1.4.0

allowBuilds:
  "@react-spring/core": true
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  sharp: true

ignoredBuiltDependencies:
  - unrs-resolver
