import type { ProjectEntry } from "../types/project"

export const projectCatalog = [
  {
    id: "01",
    title: "Copilot Task Study",
    path: "apps/copilot-task",
    updatedAt: "2026-07-11T11:20:33+08:00",
    summary:
      "A motion-led recreation of the animated Copilot Tasks preview, rebuilt in React for close study.",
    kind: "app",
    presentation: "featured",
    section: "featured",
    showcase: {
      label: "Interface study",
      note: "Unofficial study recreation",
      tags: ["React", "Motion", "Vite"],
      cover: {
        src: "/covers/copilot-task.png",
        alt: "Copilot Task Study interface preview",
        width: 1600,
        height: 900,
      },
    },
  },
  {
    id: "02",
    title: "Liminal Drift",
    path: "apps/liminal-drift",
    updatedAt: "2026-07-11T12:40:45+08:00",
    summary:
      "A dreamcore 3D driving game about pastel highways, memory fragments, and half-remembered exits.",
    kind: "app",
    presentation: "featured",
    section: "featured",
    showcase: {
      label: "Playable experiment",
      tags: ["React Three Fiber", "Three.js", "Game"],
      cover: {
        src: "/covers/liminal-drift.png",
        alt: "Liminal Drift pastel highway gameplay",
        width: 1440,
        height: 900,
      },
    },
  },
  {
    id: "03",
    title: "Maimai Transition",
    path: "apps/maimai-transition",
    updatedAt: "2026-07-11T11:20:33+08:00",
    summary:
      "A kinetic scene-swap study that turns a rhythm-game-inspired opening into a reusable transition.",
    kind: "app",
    presentation: "featured",
    section: "featured",
    showcase: {
      label: "Motion experiment",
      note: "Unofficial technical demo",
      tags: ["React", "GSAP", "Motion"],
      cover: {
        src: "/covers/maimai-transition.png",
        alt: "Maimai Transition pastel scene artwork",
        width: 1920,
        height: 1080,
      },
    },
  },
  {
    id: "04",
    title: "Shika",
    path: "apps/shika",
    updatedAt: "2026-07-11T10:08:42+08:00",
    summary:
      "A bilingual personal status page for life sections, incidents, maintenance events, and uptime notes.",
    kind: "app",
    presentation: "featured",
    section: "featured",
    showcase: {
      label: "Status prototype",
      tags: ["Next.js", "i18n", "Themes"],
      cover: {
        src: "/covers/shika.png",
        alt: "Shika personal status page preview",
        width: 1600,
        height: 900,
      },
    },
  },
  {
    id: "B-01",
    title: "Focus Orb Playground",
    path: "apps/focus-orb-demo",
    updatedAt: "2026-07-11T10:09:02+08:00",
    summary:
      "An interactive bench for tuning the WebGL orb as a focus button or ambient background.",
    status: "Demo",
    kind: "app",
    presentation: "catalog",
    section: "building",
    showcase: {
      label: "Interactive playground",
      tags: ["React", "WebGL", "Component demo"],
      cover: {
        src: "/covers/focus-orb-demo.png",
        alt: "Focus Orb Playground controls and WebGL orb",
        width: 1600,
        height: 900,
      },
    },
  },
  {
    id: "B-02",
    title: "Focus Orb",
    path: "packages/focus-orb",
    updatedAt: "2026-07-11T10:09:02+08:00",
    summary:
      "The reusable React WebGL component behind the playground, packaged for app-level composition.",
    status: "Package",
    kind: "package",
    presentation: "catalog",
    section: "building",
  },
  {
    id: "B-03",
    title: "Personal Email",
    path: "apps/personal-email",
    updatedAt: "2026-07-11T10:09:02+08:00",
    summary:
      "React Email templates and local scripts for rendering, selecting, and delivering personal mail.",
    status: "Local tool",
    kind: "app",
    presentation: "catalog",
    section: "building",
  },
  {
    id: "W-01",
    title: "NyaAI",
    path: "workbench/ai/nya-ai",
    updatedAt: "2026-07-11T10:05:30+08:00",
    summary: "OpenAI-compatible Flask chat API with switchable providers.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "ai",
  },
  {
    id: "W-02",
    title: "Auto Crawler",
    path: "workbench/automation/auto-crawler",
    updatedAt: "2026-07-11T10:05:44+08:00",
    summary: "Image-site discovery and batch-download experiment.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "automation",
  },
  {
    id: "W-03",
    title: "Clicker",
    path: "workbench/automation/clicker",
    updatedAt: "2026-07-11T10:05:44+08:00",
    summary: "Windows mouse clicker with global hotkeys and fail-safes.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "automation",
  },
  {
    id: "W-04",
    title: "Scan Image To",
    path: "workbench/files/scan-img-to",
    updatedAt: "2026-07-11T10:06:01+08:00",
    summary: "Multithreaded image scanner and copier with ignore rules.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "files",
  },
  {
    id: "W-05",
    title: "Sync Multi",
    path: "workbench/files/sync-multi",
    updatedAt: "2026-07-11T10:06:01+08:00",
    summary: "Directory watcher and deterministic multi-source backup sync.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "files",
  },
  {
    id: "W-06",
    title: "Gomoku",
    path: "workbench/games/gomoku",
    updatedAt: "2026-07-11T10:06:17+08:00",
    summary: "A 15 × 15 Gomoku game with console and desktop interfaces.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "games",
  },
  {
    id: "W-07",
    title: "Adjust GIF",
    path: "workbench/media/adjust-gif",
    updatedAt: "2026-07-11T10:06:42+08:00",
    summary: "Small desktop utility for changing GIF playback speed.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "media",
  },
  {
    id: "W-08",
    title: "Cedarflake ASCII Art",
    path: "workbench/media/ascii-art",
    updatedAt: "2026-07-11T17:48:28+08:00",
    summary: "Turn images and video into text, rendered frames, and playable ASCII video.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "media",
  },
  {
    id: "W-09",
    title: "Cut Image",
    path: "workbench/media/cut-image",
    updatedAt: "2026-07-11T10:06:42+08:00",
    summary: "Split one image into horizontal slices from the command line.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "media",
  },
  {
    id: "W-10",
    title: "Merge AV",
    path: "workbench/media/merge-av",
    updatedAt: "2026-07-11T10:06:42+08:00",
    summary: "Merge audio and video files through a focused FFmpeg wrapper.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "media",
  },
  {
    id: "W-11",
    title: "Campus Net",
    path: "workbench/network/campus-net",
    updatedAt: "2026-07-11T10:07:05+08:00",
    summary: "Ruijie campus portal auto-login utility for local use.",
    kind: "workbench",
    presentation: "workbench",
    section: "workbench",
    category: "network",
  },
  {
    id: "O-01",
    title: "Bilibili Follow Cycle",
    path: "others/userscripts/bilibili-follow-cycle",
    updatedAt: "2026-07-11T01:01:23+08:00",
    summary:
      "A browser userscript for controlled follow and unfollow cycles with interval and log panels.",
    status: "Userscript",
    kind: "other",
    presentation: "catalog",
    section: "others",
  },
  {
    id: "O-02",
    title: "GitHub Star Cycle",
    path: "others/github-actions/star-cycle",
    updatedAt: "2026-07-11T01:01:23+08:00",
    summary:
      "A retired Star and Unstar workflow experiment preserved as an intentionally inactive archive.",
    status: "Archive",
    kind: "other",
    presentation: "catalog",
    section: "others",
    isMuted: true,
  },
] as const satisfies readonly ProjectEntry[]
