import type { TemplateRolodexConfig } from "../types";
import { ASSET_BASE } from "./assets";

export const rolodexConfig: TemplateRolodexConfig = {
  introText: "With an AI Agent, teams can",
  playLabel: "Play animation",
  pauseLabel: "Pause animation",
  layouts: {
    threeLine: [
      {
        id: "1-1",
        type: "text",
        content1: "busy",
        content2: "small",
        content3: "sharp",
        row: 0,
        col: 0,
        animate: false,
      },
      {
        id: "1-2",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1a.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2a.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3a.png`,
        row: 0,
        col: 2,
      },
      {
        id: "1-3",
        type: "text",
        content1: "teams",
        content2: "tasks",
        content3: "ideas",
        row: 0,
        col: 2,
        animate: true,
      },
      {
        id: "2-1",
        type: "text",
        content1: "can",
        content2: "can",
        content3: "can",
        row: 1,
        col: 0,
        animate: false,
      },
      {
        id: "2-3",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1b.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2b.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3b.png`,
        row: 1,
        col: 2,
      },
      {
        id: "2-4",
        type: "text",
        content1: "plan",
        content2: "move",
        content3: "ship",
        row: 1,
        col: 2,
        animate: true,
      },
      {
        id: "3-1",
        type: "text",
        content1: "the",
        content2: "the",
        content3: "the",
        row: 2,
        col: 0,
        animate: false,
      },
      {
        id: "3-2",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1c.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2c.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3c.png`,
        row: 2,
        col: 2,
      },
      {
        id: "3-3",
        type: "text",
        content1: "work",
        content2: "faster",
        content3: "clearly",
        row: 2,
        col: 2,
        animate: true,
      },
    ],
    fiveLine: [
      {
        id: "1-1",
        type: "text",
        content1: "busy",
        content2: "small",
        content3: "sharp",
        row: 0,
        col: 0,
        animate: false,
      },
      {
        id: "1-2",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1a.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2a.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3a.png`,
        row: 0,
        col: 1,
      },
      {
        id: "2-1",
        type: "text",
        content1: "teams",
        content2: "tasks",
        content3: "ideas",
        row: 1,
        col: 1,
        animate: true,
      },
      {
        id: "3-1",
        type: "text",
        content1: "can",
        content2: "can",
        content3: "can",
        row: 2,
        col: 0,
        animate: false,
      },
      {
        id: "3-2",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1b.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2b.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3b.png`,
        row: 2,
        col: 1,
      },
      {
        id: "3-3",
        type: "text",
        content1: "plan",
        content2: "move",
        content3: "ship",
        row: 2,
        col: 1,
        animate: true,
      },
      {
        id: "4-1",
        type: "text",
        content1: "the",
        content2: "the",
        content3: "the",
        row: 3,
        col: 0,
        animate: false,
      },
      {
        id: "4-2",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1c.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2c.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3c.png`,
        row: 3,
        col: 1,
      },
      {
        id: "5-1",
        type: "text",
        content1: "work",
        content2: "faster",
        content3: "clearly",
        row: 4,
        col: 1,
        animate: true,
      },
    ],
    sixLine: [
      {
        id: "1-1",
        type: "text",
        content1: "busy",
        content2: "small",
        content3: "sharp",
        row: 0,
        col: 0,
        animate: false,
      },
      {
        id: "1-2",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1a.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2a.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3a.png`,
        row: 0,
        col: 1,
      },
      {
        id: "2-1",
        type: "text",
        content1: "teams",
        content2: "tasks",
        content3: "ideas",
        row: 1,
        col: 1,
        animate: true,
      },
      {
        id: "3-1",
        type: "text",
        content1: "can",
        content2: "can",
        content3: "can",
        row: 2,
        col: 0,
        animate: false,
      },
      {
        id: "3-2",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1b.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2b.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3b.png`,
        row: 2,
        col: 1,
      },
      {
        id: "4-1",
        type: "text",
        content1: "plan",
        content2: "move",
        content3: "ship",
        row: 3,
        col: 1,
        animate: true,
      },
      {
        id: "5-1",
        type: "text",
        content1: "the",
        content2: "the",
        content3: "the",
        row: 4,
        col: 0,
        animate: false,
      },
      {
        id: "5-2",
        type: "image",
        content1: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-1c.png`,
        content2: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-2c.png`,
        content3: `${ASSET_BASE}/images/tasks/waitlist/rolodex/rolodex-3c.png`,
        row: 4,
        col: 1,
      },
      {
        id: "6-1",
        type: "text",
        content1: "work",
        content2: "faster",
        content3: "clearly",
        row: 5,
        col: 1,
        animate: true,
      },
    ],
  },
};
